code_producers: Avoid race condition between C and WASM tests
Before this change, both C and WASM tests were attempting to create the
`../target/code_generator_test` directory. Rust runs tests in multiple
threads in parallel, so those tests were often failing with the
following error:

```
---- wasm_elements::wasm_code_generator::tests::produce_code stdout ----
thread 'wasm_elements::wasm_code_generator::tests::produce_code' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }', code_producers/src/wasm_elements/wasm_code_generator.rs:1656:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

That's because the C test was creating the directory in the meantime.

This change ensures that this race condition doesn't take place anymore
by using different dir names.

Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>